version: '3.3'
services:
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: zorik28/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - redoc:/app/api/docs/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: zorik28/foodgram_frontend:latest
    volumes:
      - result_build:/app/result_build/build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/static/
      - media_value:/media/
      - result_build:/usr/share/nginx/html/
      - redoc:/usr/share/nginx/html/api/docs/
    restart: always
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
  result_build:
  redoc:
